# Generated by Django 5.2.3 on 2025-06-15 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Atividade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("descricao", models.CharField(max_length=50)),
                ("horimetro_inicial", models.IntegerField()),
                ("horimetro_final", models.IntegerField()),
                ("horimetro_abastecimento", models.IntegerField()),
                ("litros_abastecimento", models.IntegerField()),
            ],
        ),
    ]
