# Generated by Django 5.2.3 on 2025-06-15 00:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("equipamentos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="equipamento",
            name="usuario",
            field=models.ManyToManyField(
                related_name="equipamento", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
