# Generated by Django 5.2.3 on 2025-06-15 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipamentos", "0003_alter_equipamento_data_manutencao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipamento",
            name="data_manutencao",
            field=models.DateField(blank=True, null=True),
        ),
    ]
