# Generated by Django 5.2.3 on 2025-06-15 01:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipamentos", "0005_alter_equipamento_usuario"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipamento",
            name="usuario",
            field=models.ManyToManyField(
                related_name="equipamentos", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
