# Generated by Django 5.2.3 on 2025-06-15 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fabricantes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Modelo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=25)),
                (
                    "fabricante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fabricantes.fabricante",
                    ),
                ),
            ],
        ),
    ]
