# Generated by Django 5.2.3 on 2025-06-15 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipamentos", "0005_alter_equipamento_usuario"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="equipamento",
            field=models.ManyToManyField(
                related_name="usuarios_relacionados", to="equipamentos.equipamento"
            ),
        ),
    ]
