# Generated by Django 5.2.3 on 2025-06-15 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_usuario_equipamento"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="equipamento",
        ),
    ]
